backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "/content/img"
public_folder: "/img"

definitions:
  fields:
    - layout: &layout-field
        {label: Layout, name: layout, widget: select, options: ['default', 'page', 'columns', 'post', 'blog', 'product-category', 'product', 'recipe']}
    - body: &body-field
        {label: Inhalt, name: body, widget: markdown}


collections:
  - label: "Jugend"
    name: jugend
    folder: "content/jugend"
    nested:
      depth: 2
    fields:
      - *layout-field
      - *body-field
  - label: "1. Mannschaft"
    name: erstemannschaft
    folder: "content/erstemannschaft"
    nested:
      depth: 2
    fields:
      - *layout-field
      - *body-field
  - label: "Verein"
    name: verein
    folder: "content/verein"
    nested:
      depth: 2
    fields:
      - *layout-field
      - *body-field
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "content/_posts" # The path to the folder where the documents are stored
    media_folder: '/content/img/news'
    public_folder: '{{public_folder}}/news'
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Header-Bild", name: "hero_image", widget: "image"}
      - {label: "Vorschau-Bild", name: "image", widget: "image"}
      - {label: "Bildquelle", name: "image_source", widget: "string", required: false}
      - {label: "Spieler", name: "players", widget: "list", required: false}
      - {label: "Coach", name: "coach", widget: "string", required: false}
      - *body-field
  - label: "Kontakt"
    name: kontakt
    folder: "content/kontakt"
    nested:
      depth: 2
    fields:
      - *layout-field
      - *body-field
  - label: "Partner"
    name: "seiten"
    files:
    - label: "Partner"
      name: partner
      file: "content/partner.md"
      fields:
        - *layout-field
        - *body-field

